// Copyright 2007, 2009, 2011, 2013 Global Virtual Airlines Group. All Rights Reserved.
package org.gvagroup.jdbc;

import java.sql.*;
import java.util.*;
import java.util.concurrent.Executor;

/**
 * A wrapper around JDBC connections returned from the Connection Pool. This prevents
 * certain sensitive methods (such as {@link Connection#close()}) from being called by
 * command code. 
 * @author Luke
 * @version 1.7
 * @since 1.0
 */

public class ConnectionWrapper implements Connection, Comparable<ConnectionWrapper> {
	
	private final Integer _id;
	private final boolean _isMySQL;
	private transient final Connection _c;
	private transient final ConnectionPoolEntry _entry;
	
	private boolean _autoCommit;

	/**
	 * Creates the wrapper.
	 * @param cpe the ConnectionPoolEntry to wrap
	 */
	ConnectionWrapper(Connection c, ConnectionPoolEntry cpe) {
		super();
		_c = c;
		_id = Integer.valueOf(cpe.getID());
		_entry = cpe;
		// TODO: Detect this
		_isMySQL = true;
	}
	
	/**
	 * Returns the Connection Pool ID for this Connection
	 * @return the ID
	 * @see ConnectionPoolEntry#getID()
	 */
	public Integer getID() {
		return _id;
	}

	@Override
	public void clearWarnings() throws SQLException {
		_c.clearWarnings();
	}

	@Override
	public void close() {
		_entry.free();
	}
	
	void forceClose() throws SQLException {
		_c.close();
	}
	
	Connection getConnection() {
		return _c;
	}

	@Override
	public void commit() throws SQLException {
		_c.commit();
	}

	@Override
	public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
		return _c.createArrayOf(typeName, elements);
	}

	@Override
	public Blob createBlob() throws SQLException {
		return _c.createBlob();
	}

	@Override
	public Clob createClob() throws SQLException {
		return _c.createClob();
	}

	@Override
	public NClob createNClob() throws SQLException {
		return _c.createNClob();
	}

	@Override
	public SQLXML createSQLXML() throws SQLException {
		return _c.createSQLXML();
	}

	@Override
	public Statement createStatement() throws SQLException {
		return _c.createStatement();
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		return _c.createStatement(resultSetType, resultSetConcurrency);
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return _c.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	@Override
	public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
		return _c.createStruct(typeName, attributes);
	}

	@Override
	public boolean getAutoCommit() throws SQLException {
		return _autoCommit;
	}

	@Override
	public String getCatalog() throws SQLException {
		return _c.getCatalog();
	}

	@Override
	public Properties getClientInfo() throws SQLException {
		return _c.getClientInfo();
	}

	@Override
	public String getClientInfo(String name) throws SQLException {
		return _c.getClientInfo(name);
	}

	@Override
	public int getHoldability() throws SQLException {
		return _c.getHoldability();
	}

	@Override
	public DatabaseMetaData getMetaData() throws SQLException {
		return _c.getMetaData();
	}

	@Override
	public int getTransactionIsolation() throws SQLException {
		return _c.getTransactionIsolation();
	}

	@Override
	public Map<String, Class<?>> getTypeMap() throws SQLException {
		return _c.getTypeMap();
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		return _c.getWarnings();
	}

	@Override
	public boolean isClosed() throws SQLException {
		return _c.isClosed();
	}

	@Override
	public boolean isReadOnly() {
		return false;
	}

	@Override
	public boolean isValid(int timeout) throws SQLException {
		return _c.isValid(timeout);
	}

	@Override
	public String nativeSQL(String sql) throws SQLException {
		return _c.nativeSQL(sql);
	}

	@Override
	public CallableStatement prepareCall(String sql) throws SQLException {
		return _c.prepareCall(sql);
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return _c.prepareCall(sql, resultSetType, resultSetConcurrency);
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return _c.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return _c.prepareStatement(sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		return _c.prepareStatement(sql, autoGeneratedKeys);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		return _c.prepareStatement(sql, columnIndexes);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		return _c.prepareStatement(sql, columnNames);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return _c.prepareStatement(sql, resultSetType, resultSetConcurrency);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return _c.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	@Override
	public void releaseSavepoint(Savepoint savepoint) throws SQLException {
		_c.releaseSavepoint(savepoint);
	}

	@Override
	public void rollback() throws SQLException {
		_c.rollback();
	}

	@Override
	public void rollback(Savepoint savepoint) throws SQLException {
		_c.rollback(savepoint);
	}

	@Override
	public void setAutoCommit(boolean autoCommit) throws SQLException {
		_autoCommit = autoCommit;
		_c.setAutoCommit(_autoCommit);
	}

	@Override
	public void setCatalog(String catalog) throws SQLException {
		_c.setCatalog(catalog);
	}

	@Override
	public void setClientInfo(Properties properties) throws SQLClientInfoException {
		_c.setClientInfo(properties);
	}

	@Override
	public void setClientInfo(String name, String value) throws SQLClientInfoException {
		_c.setClientInfo(name, value);
	}

	@Override
	public void setHoldability(int holdability) throws SQLException {
		_c.setHoldability(holdability);
	}

	@Override
	public void setReadOnly(boolean readOnly) throws SQLException {
		// nothing
	}

	@Override
	public Savepoint setSavepoint() throws SQLException {
		return _c.setSavepoint();
	}

	@Override
	public Savepoint setSavepoint(String name) throws SQLException {
		return _c.setSavepoint(name);
	}

	@Override
	public void setTransactionIsolation(int level) throws SQLException {
		// nothing
	}

	@Override
	public void setTypeMap(Map<String, Class<?>> m) throws SQLException {
		_c.setTypeMap(m);
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return _c.isWrapperFor(iface);
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		return _c.unwrap(iface);
	}
	
	public int compareTo(ConnectionWrapper cw2) {
		return _id.compareTo(cw2._id);
	}

	public int hashCode() {
		return toString().hashCode();
	}
	
	public String toString() {
		return "ConnectionWrapper-" + String.valueOf(_id);
	}

	@Override
	public void setSchema(String schema) throws SQLException {
		_c.setSchema(schema);
	}

	@Override
	public String getSchema() throws SQLException {
		return _c.getSchema();
	}

	@Override
	public void abort(Executor executor) throws SQLException {
		_c.abort(executor);
	}

	@Override
	public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
		_c.setNetworkTimeout(executor, milliseconds);
	}

	@Override
	public int getNetworkTimeout() throws SQLException {
		return _c.getNetworkTimeout();
	}
}