// Copyright 2007, 2009 Global Virtual Airlines Group. All Rights Reserved.
package org.gvagroup.jdbc;

import java.sql.*;
import java.util.*;

/**
 * A wrapper around JDBC connections returned from the Connection Pool. This prevents
 * certain sensitive methods (such as {@link Connection#close()}) from being called by
 * command code. 
 * @author Luke
 * @version 2.6
 * @since 2.0
 */

public class ConnectionWrapper implements Connection, Comparable<ConnectionWrapper> {
	
	private Integer _id;
	private boolean _autoCommit;
	private transient Connection _c;
	private transient ConnectionPoolEntry _entry;

	/**
	 * Creates the wrapper.
	 * @param cpe the ConnectionPoolEntry to wrap
	 */
	ConnectionWrapper(Connection c, ConnectionPoolEntry cpe) {
		super();
		_c = c;
		_id = Integer.valueOf(cpe.getID());
		_entry = cpe;
	}
	
	/**
	 * Returns the Connection Pool ID for this Connection
	 * @return the ID
	 * @see ConnectionPoolEntry#getID()
	 */
	public Integer getID() {
		return _id;
	}

	public void clearWarnings() throws SQLException {
		_c.clearWarnings();
	}

	public void close() {
		_entry.free();
	}
	
	void forceClose() throws SQLException {
		_c.close();
	}
	
	Connection getConnection() {
		return _c;
	}

	public void commit() throws SQLException {
		_c.commit();
	}

	public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
		return _c.createArrayOf(typeName, elements);
	}

	public Blob createBlob() throws SQLException {
		return _c.createBlob();
	}

	public Clob createClob() throws SQLException {
		return _c.createClob();
	}

	public NClob createNClob() throws SQLException {
		return _c.createNClob();
	}

	public SQLXML createSQLXML() throws SQLException {
		return _c.createSQLXML();
	}

	public Statement createStatement() throws SQLException {
		return _c.createStatement();
	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		return _c.createStatement(resultSetType, resultSetConcurrency);
	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return _c.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
		return _c.createStruct(typeName, attributes);
	}

	public boolean getAutoCommit() throws SQLException {
		return _autoCommit;
	}

	public String getCatalog() throws SQLException {
		return _c.getCatalog();
	}

	public Properties getClientInfo() throws SQLException {
		return _c.getClientInfo();
	}

	public String getClientInfo(String name) throws SQLException {
		return _c.getClientInfo(name);
	}

	public int getHoldability() throws SQLException {
		return _c.getHoldability();
	}

	public DatabaseMetaData getMetaData() throws SQLException {
		return _c.getMetaData();
	}

	public int getTransactionIsolation() throws SQLException {
		return _c.getTransactionIsolation();
	}

	public Map<String, Class<?>> getTypeMap() throws SQLException {
		return _c.getTypeMap();
	}

	public SQLWarning getWarnings() throws SQLException {
		return _c.getWarnings();
	}

	public boolean isClosed() throws SQLException {
		return _c.isClosed();
	}

	public boolean isReadOnly() {
		return false;
	}

	public boolean isValid(int timeout) throws SQLException {
		return _c.isValid(timeout);
	}

	public String nativeSQL(String sql) throws SQLException {
		return _c.nativeSQL(sql);
	}

	public CallableStatement prepareCall(String sql) throws SQLException {
		return _c.prepareCall(sql);
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return _c.prepareCall(sql, resultSetType, resultSetConcurrency);
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {
		return _c.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return _c.prepareStatement(sql);
	}

	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		return _c.prepareStatement(sql, autoGeneratedKeys);
	}

	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		return _c.prepareStatement(sql, columnIndexes);
	}

	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		return _c.prepareStatement(sql, columnNames);
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return _c.prepareStatement(sql, resultSetType, resultSetConcurrency);
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {
		return _c.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	public void releaseSavepoint(Savepoint savepoint) throws SQLException {
		_c.releaseSavepoint(savepoint);
	}

	public void rollback() throws SQLException {
		_c.rollback();
	}

	public void rollback(Savepoint savepoint) throws SQLException {
		_c.rollback(savepoint);
	}

	public void setAutoCommit(boolean autoCommit) throws SQLException {
		_autoCommit = autoCommit;
		_c.setAutoCommit(_autoCommit);
	}

	public void setCatalog(String catalog) throws SQLException {
		_c.setCatalog(catalog);
	}

	public void setClientInfo(Properties properties) throws SQLClientInfoException {
		_c.setClientInfo(properties);
	}

	public void setClientInfo(String name, String value) throws SQLClientInfoException {
		_c.setClientInfo(name, value);
	}

	public void setHoldability(int holdability) throws SQLException {
		_c.setHoldability(holdability);
	}

	public void setReadOnly(boolean readOnly) throws SQLException {
		// nothing
	}

	public Savepoint setSavepoint() throws SQLException {
		return _c.setSavepoint();
	}

	public Savepoint setSavepoint(String name) throws SQLException {
		return _c.setSavepoint(name);
	}

	public void setTransactionIsolation(int level) throws SQLException {
		// nothing
	}

	public void setTypeMap(Map<String, Class<?>> m) throws SQLException {
		_c.setTypeMap(m);
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return _c.isWrapperFor(iface);
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		return _c.unwrap(iface);
	}
	
	public int compareTo(ConnectionWrapper cw2) {
		return _id.compareTo(cw2._id);
	}

	public int hashCode() {
		return toString().hashCode();
	}
	
	public String toString() {
		return "ConnectionWrapper-" + String.valueOf(_id);
	}
}